name: ci

on:
  push:
      branches:
        - 'feature/*'

jobs:
  build_and_push:
    runs-on: ubuntu-18.04
    env:
        user: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASS}}
    steps:
      - uses: actions/checkout@v2

      - name: mvn clean and install
        run: mvn clean install

      - name: login docker
        run: docker login -u $user -p $password

      - name: build images
        run: docker build . -t zurdenro/my-app:latest

      - name: push images
        run: docker push zurdenro/my-app:latest